//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMst
    {
        public int ID { get; set; }
        public int ModuleID { get; set; }
        public int ScreeningGroupID { get; set; }
        public string ModuleOriginalName { get; set; }
        public string ModuleOriginalName_Dan { get; set; }
        public string ModuleOriginalName_Esp { get; set; }
        public string ModuleOriginalName_Dut { get; set; }
        public string ModuleOriginalName_Kor { get; set; }
        public string ModuleName { get; set; }
        public Nullable<int> ScreeningOrder { get; set; }
        public string Route { get; set; }
        public Nullable<int> supplementTotalQuestion { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
