//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_WithAngular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionMst
    {
        public long QuestionID { get; set; }
        public Nullable<int> ScreeningGroupId { get; set; }
        public int ModuleID { get; set; }
        public Nullable<int> SymptomID { get; set; }
        public string Sub_Symptom { get; set; }
        public string QuestionSequenceID { get; set; }
        public string QuestionText { get; set; }
        public string QuestionText_Parent { get; set; }
        public string QuestionText_Dan { get; set; }
        public string QuestionText_Parent_Dan { get; set; }
        public string QuestionText_Esp { get; set; }
        public string QuestionText_Parent_Esp { get; set; }
        public string QuestionText_Dut { get; set; }
        public string QuestionText_Parent_Dut { get; set; }
        public string QuestionText_Kor { get; set; }
        public string QuestionText_Parent_Kor { get; set; }
        public string Video { get; set; }
        public string QuestionType { get; set; }
        public Nullable<int> AnswerID { get; set; }
        public Nullable<int> TotalRoutes { get; set; }
        public string BranchingLogic { get; set; }
        public string Condition1 { get; set; }
        public string Route1 { get; set; }
        public string Condition2 { get; set; }
        public string Route2 { get; set; }
        public string Condition3 { get; set; }
        public string Route3 { get; set; }
        public string Condition4 { get; set; }
        public string Route4 { get; set; }
        public bool Active { get; set; }
        public Nullable<int> FunctionID { get; set; }
    }
}
